pipeline {
    agent any

    parameters {
        choice(name: 'TERRAFORM_ACTION', choices: ['init', 'plan', 'apply', 'destroy'], description: 'Select Terraform action')
        choice(name: 'APPLICATION', choices: ['java', 'python', 'net'], description: 'Select the application type')
        choice(name: 'ENVIRONMENT', choices: ['dev', 'qa', 'prod'], description: 'Select the environment')
        string(name: 'INSTANCE_COUNT', description: 'Number of instances to create...This is only required for terraform plan')
    }

    environment {
        AWS_REGION = 'us-east-1' // ununsed variables
        TF_WORKING_DIR = 'ec2'  // Update this if your Terraform files are in a different directory
    }

    stages {
        stage('Terraform Init') {
            when {
                expression { params.TERRAFORM_ACTION == 'init' }
            }
            steps {
                dir("${TF_WORKING_DIR}") {
                    sh 'terraform init'
                }
            }
        }

        stage ('Slack Notification for Terraform init') {
            when {
                expression { params.TERRAFORM_ACTION == 'init' }
            }
          steps {
            echo "terraform init command has successfully ran"
            slackSend(channel:'devop-spring', message: "Job is successful, here is the info - Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]' (${env.BUILD_URL})")
          }
        }

        stage('Terraform Plan') {
            when {
                expression { params.TERRAFORM_ACTION == 'plan' }
            }
            steps {
                dir("${TF_WORKING_DIR}") {
                    sh """
                        terraform plan -out=tfplan \
                        -var="application=${params.APPLICATION}" \
                        -var="environment=${params.ENVIRONMENT}" \
                        -var="instance_count=${params.INSTANCE_COUNT}" \
                        -var="security_group=aws-${params.ENVIRONMENT}-${params.APPLICATION}-sg"

                    """
                }
            }
        }
        
        stage('Terraform Plan && Apply') {
            when {
                expression { params.TERRAFORM_ACTION == 'apply' }
            }
            steps {
                dir("${TF_WORKING_DIR}") {
                    script {
                        if (fileExists("tfplan")) {
                            echo "Applying Terraform changes..."
                            sh """
                                terraform apply -auto-approve tfplan
                            """
                        } else {
                            error "Terraform plan file does not exist. Run the 'plan' stage first."
                        }
                    }
                }
            }
        }

        stage ('Slack Notification for Terraform Apply') {
            when {
                expression { params.TERRAFORM_ACTION == 'apply' }
            }
          steps {
            echo "terraform apply command has successfully ran. ${params.INSTANCE_COUNT} number of Instances have been provisioned "
            slackSend(channel:'devop-spring', message: "Job is successful, ${params.INSTANCE_COUNT} number of Instances have been provisioned here is the info - Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]' (${env.BUILD_URL})")
          }
        }

        stage('Terraform Destroy') {
            when {
                expression { params.TERRAFORM_ACTION == 'destroy' }
            }
            steps {
                dir("${TF_WORKING_DIR}") {
                    sh """
                        terraform destroy -auto-approve \
                        -var="application=${params.APPLICATION}" \
                        -var="environment=${params.ENVIRONMENT}" \
                        -var="instance_count=${params.INSTANCE_COUNT}" \
                        -var="security_group=aws-${params.ENVIRONMENT}-${params.APPLICATION}-sg"
                    """
                }
            }
        }
        
        // stage ('Slack Notification') {
        //   steps {
        //     echo "terraform script has been successfully deployed"
        //     slackSend(channel:'devop-spring', message: "Job is successful, here is the info - Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]' (${env.BUILD_URL})")
        //   }
        // }
    }

    post {
            always {
            // Clean up workspace
            cleanWs()
        }
    }
}
